= MidPoint Studio
:sectnums:
:toc:
:toclevels: 4
:toc-title: Table of Contents

== Overview

Plugin for Intellij Idea to help identity engineers customize https://midpoint.evolveum.com[MidPoint] identity management solution by https://evolveum.com[Evolveum].

== Features

* MidPoint objects manipulation
** Browse, upload objects
** Execute tasks, actions
** Test resources
* Documentation generator
* Debugger for Groovy scripts expressions
* IDE editor capabilities
** Completions
** Annotations
** Reference integrity checks
** Random OID generator
** Schema documentation
** File Templates
* Support for multiple environments
* Master password encryption for passwords and other secret values

== Documentation

Documentation is available https://docs.evolveum.com/midpoint/studio/[here].

== Installation

It's available in JetBrains Marketplace https://plugins.jetbrains.com/plugin/13809-midpoint-studio[here].
Installation steps:

. Start Intellij Idea (Community/Ultimate)
. Go to menu *File -> Settings (Preferences) -> Plugins*
. For stable releases, they are directly available
.. Search for "MidPoint Studio" -> Install
. For other releases
.. Go to *Manage plugin repositories*
.. Snapshot releases (unreleased new major release)
... Add repository `https://plugins.jetbrains.com/plugins/Snapshot/list`
.. Support releases (unreleased new patch release)
... Add repository `https://plugins.jetbrains.com/plugins/Support/list`
.. Save & Close dialog
.. Search for "MidPoint Studio" -> Install

== Issues, Bugs

You're welcome to file bugs, new feature request or other issues in our issue tracker https://support.evolveum.com[support].
Please don't forget add this information to new issue:

* Add component `Studio`
* Describe plugin version and Intellij version, OS related information
* Attach necessary logs, e.g. idea.log => can be found using menu *Help -> Show log in Finder*

== Development Notes

=== Git Branches

* Main development branch -> `master` for next major release
* Support/maintenance branch -> `support-X.Y` for current stable release X.Y.*

=== Versions and Releases

* Releases -> `<major.minor.patch>`, e.g. `4.9.0`
* Snapshot builds -> `<major.minor.patch>-snapshot-<build_number>`, e.g. `4.10.0-snapshot-60`
* Support builds -> `<major.minor.patch>-support-<build_number>`, e.g. `4.8.2-support-78`

Versioning scheme for major and minor version aligns to MidPoint releases.
MidPoint Studio release 4.6.* will use 4.6 libraries from MidPoint project.

Each type of release (stable, snapshot, support) is published to https://plugins.jetbrains.com/plugin/13809-midpoint-studio[JetBrains Marketplace].

=== Logging settings

Intellij Idea logs to file `studio-idea-plugin/build/idea-sandbox/system/log/idea.log`.
Logging settings can be changed during runtime via top menu `Help/Debug Log Settings` by adding packages/classes on each line in format:

* `#LOGGER` to log LOGGER (package or class) on DEBUG level
* `#LOGGER:trace` to log LOGGER (package or class) on TRACE level

== License

Project is licensed under Apache Licence 2.0.
See LICENSE file for more details.
