= TODO

* EnvironmentManagerImpl.getSelected() always reads credentials keepass file (full environment), multiple times pre second only to get color
* MidPointXmlStructureViewBuilderProvider not finished
* Finish jira issue submitting (error reporting)
* Passwords
* resource templates and rethink whole create resource process
* make different midpoint versions as distributions and load them via custom classpath
** user of plugin can then pick midpoint version with everything for himself (proper xsd versions, proper client version, etc.)
* Credentials manager needs keyring pwd too often
* Icons
** to svg
*** midpoint logo
* Some simple UI to setup different monitor probes (per environment). For example, checks like:
** Task status (running/suspended/closed)
** Task stalled
** Nodes in cluster available
** Livesync task token parsing and validation (for example whether task is not too much behind)
** Resource going up/down + reason
* "Samples" toolbar action button
** shows somehow indexed midpoint-samples for simple search
