= TODO

* EnvironmentManagerImpl.getSelected() always reads credentials keepass file (full environment), multiple times pre second only to get color
* MidPointXmlStructureViewBuilderProvider not finished
* Toolbar menu icons [wip]
* Upload/Execute of scripts doesn't work
* Finish jira issue submitting (error reporting)
* Cluster tool window for healt checking
* Transform components to services
* Implement action that will allow import one account from resource and then unlink
* settings for master password not visible in project/module settings
* where do we store environment username/password? -> regression, they are not stsored in keepass2
* master password reset
* what if master password was not set? ask for credentials?
* resource templates and rethink whole create resource process
* make different midpoint versions as distributions and load them via custom classpath
** user of plugin can then pick midpoint version with everything for himself (proper xsd versions, proper client version, etc.)
* FeatureUsageTracker.getInstance() can be used probably to track statistics
** credentials manager needs keyring pwd too often
* Icons
** to svg
*** midpoint logo
*** logFolder-left (fix)
*** generate oid action
