= TODO

* EnvironmentManagerImpl.getSelected() always reads credentials keepass file (full environment), multiple times pre second only to get color
* MidPointXmlStructureViewBuilderProvider not finished
* Finish jira issue submitting (error reporting)
* Implement action that will allow import one account from resource and then unlink
* Passwords
** what if master password was not set? ask for credentials?
* resource templates and rethink whole create resource process
* make different midpoint versions as distributions and load them via custom classpath
** user of plugin can then pick midpoint version with everything for himself (proper xsd versions, proper client version, etc.)
* FeatureUsageTracker.getInstance() can be used probably to track statistics
* Credentials manager needs keyring pwd too often
* Icons
** to svg
*** midpoint logo
*** generate oid action
* Some simple UI to setup different monitor probes (per environment). For example, checks like:
** Task status (running/suspended/closed)
** Task stalled
** Nodes in cluster available
** Livesync task token parsing and validation (for example whether task is not too much behind)
** Resource going up/down + reason
* Midpoint client
** there could be some parsing checks afterwards if needed/wanted
* how to import existing eclipse projects?
* better error message for resource upload when there's wrong connectorRef (returns error 500)
* new action "patch" or update operation which can use ObjectDeltaType
* "Samples" toolbar action button
** shows somehow indexed midpoint-samples for simple search
